import './style.css'
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  weight: ['400', '600', '800'],
  subsets: ['latin']
})

export const metadata = {
  title: 'List of Universities',
  description: 'Generated by Fola using create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className= 'body' >{children}</body>
    </html>
  )
}
